# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qu3W0LJOb6bzZqTUqzitohh1_1ycmxRg
"""

from sklearn.linear_model import LinearRegression

x=[[1],[2],[3],[4],[5]]
y=[12,22,33,44,55]

model=LinearRegression()
model.fit(x,y)
prediction=model.predict([[6]])
print(f"predicted value:{prediction[0]}")

from sklearn.cluster import KMeans
import numpy as np
X=np.array([[1,2],[1,3],[1,6],[10,9],[10,7],[10,5]])

Kmeans=KMeans(n_clusters=4,random_state=1).fit(X)
print(f"cluster centers:\n{Kmeans.cluster_centers_}")

from sklearn import datasets
import mathplotlib.pyplot as plt

iris_df = datasets.load_iris()
from sklearn import datasets
import matplotlib.pyplot as plt

iris_df = datasets.load_iris()

print(dir(iris_df))
print(iris_df.feature_names)
print(iris_df.target)
print(iris_df.target_names)

label={0:"red",1:"blue",2:"green"}

x_axis=iris_df.data[:,0]
y_axis=iris_df.data[:,1]

plt.scatter(x_axis,y_axis,c=iris_df.target)
plt.show()

label={0:"red",1:"blue",2:"green"}

x_axis=iris_df.data[:,0]
y_axis=iris_df.data[:,1]

plt.scatter[x_axis,y_axis,c=iris_df.target]
plt.show()